'use strict';

module.exports = function (/*app*/) {
  return {
    /////////////
    // GENERAL //
    /////////////
    API_VALIDATION_ERROR: 400,
    UPLOAD_ERROR: 401,
    UNKNOWN_ERROR: 402,
    N0_ACCESS: 403,
    IMAGE_NOT_FOUND: 404,

    ////////////
    // COMMON //
    ////////////
    INVALID_FILE_TYPE: 501,
    NO_USER_ACCESS: 502,

    //////////
    // AUTH //
    //////////
    SESSION_NOT_FOUND: 1000,
    OTP_INVALID: 1001,
    OTP_TIMEDOUT: 1002,
    PASSWORD_MISMATCH: 1003,
    SOCIAL_ID_NOT_FOUND: 1004,
    ACCESS_TOKEN_EXPIRED: 1005,
    REFRESH_TOKEN_EXPIRED: 1006,
    TOKEN_INVALID: 1007,
    TOKEN_TIMEDOUT: 1008,
    INVALID_PIN: 1009,

    ////////////
    // ADMIN  //
    ////////////
    ADMIN_NOT_FOUND: 1100,
    ADMIN_HAS_BEEN_SUSPENDED: 1101,
    ADMIN_EMAIL_ALREADY_EXISTS: 1102,
    ADMIN_HAS_BEEN_DELETED: 1103,
    ADMIN_BLOCKED_BY_ADMIN: 1104,
    ROLE_ALREADY_EXISTS: 1105,
    ADMIN_ALREADY_EXISTS_FOR_THIS_ROLE: 1106,

    ///////////
    // USER //
    /////////
    USER_NOT_FOUND: 1200,
    USER_HAS_BEEN_SUSPENDED: 1201,
    USER_ALREADY_EXISTS: 1202,
    USER_HAS_BEEN_DELETED: 1203,
    USER_BLOCKED_BY_ADMIN: 1204,
    USER_BLOCKED: 1205,
    USER_IS_ALREADY_REGISTERED: 1206,
    USER_DELETED: 1207,
    USER_IS_SOCIAL_REGISTERED: 1208,
    USER_ALREADY_REGISTERED_DIFFERENT_SOCIAL_ACCOUNT: 1209,
    DEVICE_NOT_REGISTERED: 1210,
    INVALID_REGISTRATION_CODE: 1211,
    REGISTRATION_CODE_MAX_ATTEMPT_REACHED: 1212,
    // LANGUAGE
    LANGUAGE_ALREADY_EXISTS: 1301,

    // CATEGORY
    CATEGORY_ALREADY_EXISTS: 1311,
    CATEGORY_NOT_FOUND: 1312,
    CATEGORY_CANNOT_BE_DELETED_DUE_TO_STOCK: 1313,

    //FAQ
    FAQ_ALREADY_EXISTS: 1381,

    ///////////////////
    // GLOBAL CONFIG //
    ///////////////////
    GLOBAL_CONFIG_NOT_FOUND: 1400,

    ////////////////////////
    // RESTAURANT OWNER  //
    ////////////////////////
    RESTAURANT_OWNER_NOT_FOUND: 1500,
    RESTAURANT_OWNER_HAS_BEEN_SUSPENDED: 1501,
    RESTAURANT_OWNER_EMAIL_ALREADY_EXISTS: 1502,
    RESTAURANT_OWNER_HAS_BEEN_DELETED: 1503,
    RESTAURANT_OWNER_BLOCKED_BY_ADMIN: 1504,
    ROLE_ALREADY_EXISTS: 1505,
    RESTAURANT_OWNER_ALREADY_EXISTS_FOR_THIS_ROLE: 1506,
    RESTAURANT_OWNER_IS_SOCIAL_REGISTERED: 1507,
    MEMBER_CANNOT_BE_DELETED: 1508,
    RESTAURANT_OWNER_CANNOT_BE_SUSPENDED: 1509,

    RESTAURANT_ALREADY_EXISTS: 1550,

    MENU_ALREADY_EXISTS: 1600,
    MENU_NOT_FOUND: 1601,
    MENU_ITEM_CANNOT_BE_DELETED: 1602,

    // ORDER
    ORDER_ALREADY_EXISTS: 1650,
    ORDER_NOT_FOUND: 1651,
    ORDER_CANNOT_BE_CANCELLED: 1652,

    // INVENTORY
    INVENTORY_ALREADY_EXISTS: 1700,
    INVENTORY_NOT_FOUND: 1701,
    NOT_ENOUGH_STOCK: 1702,

    BILL_NOT_FOUND: 1750,

    TABLE_ALREADY_EXISTS: 1800,
    TABLE_NOT_FOUND: 1801,
    TABLE_CANNOT_BE_DELETED: 1802,

    TABLE_SESSION_NOT_FOUND: 1850,
    TABLE_ALREADY_ORDER: 1851,

    FEEDBACK_NOT_FOUND: 1900,

    QUERY_NOT_FOUND: 1950,

    EXPENSE_NOT_FOUND: 2000,

    PLAN_ALREADY_EXISTS: 2050,
  };
};
