export const inventoryCategories = [
  { "name": "Vegetables" },
  { "name": "Fruits" },
  { "name": "Leafy Greens" },
  { "name": "Pulses & Lentils" },
  { "name": "Grains & Rice" },
  { "name": "Flours & Cereals" },
  { "name": "Spices & Masalas" },
  { "name": "Herbs & Seasonings" },
  { "name": "Oils & Fats" },
  { "name": "Dairy & Milk Products" },
  { "name": "Bread & Bakery Raw" },
  { "name": "Meat" },
  { "name": "Poultry" },
  { "name": "Seafood" },
  { "name": "Eggs & Egg Products" },
  { "name": "Sauces & Pastes" },
  { "name": "Ready Mix / Premix" },
  { "name": "Canned & Preserved Goods" },
  { "name": "Frozen Raw Materials" },
  { "name": "Dry Fruits & Nuts" },
  { "name": "Cleaning & Consumables" },
  { "name": "Packaging Materials" },
  { "name": "Disposables" },
  { "name": "Chemicals (Kitchen Use)" }
]

export const inventoryItems = [
  {"name":"Tomato","unit":1,"saveAsUnit":2,"categoryName":"Vegetables"},
  {"name":"Onion","unit":1,"saveAsUnit":2,"categoryName":"Vegetables"},
  {"name":"Potato","unit":1,"saveAsUnit":2,"categoryName":"Vegetables"},
  {"name":"Carrot","unit":1,"saveAsUnit":2,"categoryName":"Vegetables"},
  {"name":"Beetroot","unit":1,"saveAsUnit":2,"categoryName":"Vegetables"},
  {"name":"Cabbage","unit":1,"saveAsUnit":2,"categoryName":"Vegetables"},
  {"name":"Cauliflower","unit":1,"saveAsUnit":2,"categoryName":"Vegetables"},
  {"name":"Capsicum (Bell Pepper)","unit":1,"saveAsUnit":2,"categoryName":"Vegetables"},
  {"name":"Broccoli","unit":1,"saveAsUnit":2,"categoryName":"Vegetables"},
  {"name":"Mushroom","unit":1,"saveAsUnit":2,"categoryName":"Vegetables"},
  {"name":"French Beans","unit":1,"saveAsUnit":2,"categoryName":"Vegetables"},
  {"name":"Green Peas","unit":1,"saveAsUnit":2,"categoryName":"Vegetables"},
  {"name":"Bottle Gourd","unit":1,"saveAsUnit":2,"categoryName":"Vegetables"},
  {"name":"Bitter Gourd","unit":1,"saveAsUnit":2,"categoryName":"Vegetables"},
  {"name":"Drumstick","unit":1,"saveAsUnit":2,"categoryName":"Vegetables"},
  {"name":"Pumpkin","unit":1,"saveAsUnit":2,"categoryName":"Vegetables"},
  {"name":"Corn (Sweet Corn)","unit":1,"saveAsUnit":2,"categoryName":"Vegetables"},
  {"name":"Baby Corn","unit":1,"saveAsUnit":2,"categoryName":"Vegetables"},
  {"name":"Zucchini","unit":1,"saveAsUnit":2,"categoryName":"Vegetables"},
  {"name":"Eggplant (Brinjal)","unit":1,"saveAsUnit":2,"categoryName":"Vegetables"},
  {"name":"Yam","unit":1,"saveAsUnit":2,"categoryName":"Vegetables"},
  {"name":"Taro (Arbi)","unit":1,"saveAsUnit":2,"categoryName":"Vegetables"},
  {"name":"Radish","unit":1,"saveAsUnit":2,"categoryName":"Vegetables"},
  {"name":"Sweet Potato","unit":1,"saveAsUnit":2,"categoryName":"Vegetables"},
  {"name":"Green Chilli","unit":1,"saveAsUnit":1,"categoryName":"Vegetables"},
  {"name":"Ginger","unit":1,"saveAsUnit":1,"categoryName":"Vegetables"},
  {"name":"Garlic","unit":1,"saveAsUnit":1,"categoryName":"Vegetables"},
  {"name":"Spring Onion","unit":1,"saveAsUnit":2,"categoryName":"Vegetables"},
  {"name":"Okra (Bhindi)","unit":1,"saveAsUnit":2,"categoryName":"Vegetables"},
  {"name":"Kohlrabi (Knol Khol)","unit":1,"saveAsUnit":2,"categoryName":"Vegetables"},
  {"name":"Leek","unit":1,"saveAsUnit":2,"categoryName":"Vegetables"},

  {"name":"Apple","unit":1,"saveAsUnit":2,"categoryName":"Fruits"},
  {"name":"Banana","unit":1,"saveAsUnit":2,"categoryName":"Fruits"},
  {"name":"Orange","unit":1,"saveAsUnit":2,"categoryName":"Fruits"},
  {"name":"Mango","unit":1,"saveAsUnit":2,"categoryName":"Fruits"},
  {"name":"Pineapple","unit":1,"saveAsUnit":2,"categoryName":"Fruits"},
  {"name":"Pomegranate","unit":1,"saveAsUnit":2,"categoryName":"Fruits"},
  {"name":"Grapes","unit":1,"saveAsUnit":2,"categoryName":"Fruits"},
  {"name":"Lemon","unit":1,"saveAsUnit":2,"categoryName":"Fruits"},
  {"name":"Watermelon","unit":1,"saveAsUnit":2,"categoryName":"Fruits"},
  {"name":"Papaya","unit":1,"saveAsUnit":2,"categoryName":"Fruits"},
  {"name":"Kiwi","unit":1,"saveAsUnit":2,"categoryName":"Fruits"},
  {"name":"Strawberry","unit":1,"saveAsUnit":2,"categoryName":"Fruits"},
  {"name":"Blueberry","unit":1,"saveAsUnit":2,"categoryName":"Fruits"},
  {"name":"Avocado","unit":1,"saveAsUnit":2,"categoryName":"Fruits"},

  {"name":"Spinach","unit":1,"saveAsUnit":2,"categoryName":"Leafy Greens"},
  {"name":"Lettuce (Iceberg)","unit":1,"saveAsUnit":2,"categoryName":"Leafy Greens"},
  {"name":"Romaine Lettuce","unit":1,"saveAsUnit":2,"categoryName":"Leafy Greens"},
  {"name":"Arugula (Rocket)","unit":1,"saveAsUnit":2,"categoryName":"Leafy Greens"},
  {"name":"Mustard Greens","unit":1,"saveAsUnit":2,"categoryName":"Leafy Greens"},
  {"name":"Fenugreek Leaves (Methi)","unit":1,"saveAsUnit":2,"categoryName":"Leafy Greens"},
  {"name":"Coriander Leaves","unit":1,"saveAsUnit":2,"categoryName":"Leafy Greens"},
  {"name":"Mint Leaves","unit":1,"saveAsUnit":2,"categoryName":"Leafy Greens"},

  {"name":"Red Kidney Beans (Rajma)","unit":1,"saveAsUnit":2,"categoryName":"Pulses & Lentils"},
  {"name":"Chickpeas (Chole)","unit":1,"saveAsUnit":2,"categoryName":"Pulses & Lentils"},
  {"name":"Toor Dal","unit":1,"saveAsUnit":2,"categoryName":"Pulses & Lentils"},
  {"name":"Moong Dal","unit":1,"saveAsUnit":2,"categoryName":"Pulses & Lentils"},
  {"name":"Urad Dal","unit":1,"saveAsUnit":2,"categoryName":"Pulses & Lentils"},
  {"name":"Chana Dal","unit":1,"saveAsUnit":2,"categoryName":"Pulses & Lentils"},
  {"name":"Masoor Dal","unit":1,"saveAsUnit":2,"categoryName":"Pulses & Lentils"},
  {"name":"Black Gram","unit":1,"saveAsUnit":2,"categoryName":"Pulses & Lentils"},
  {"name":"Split Peas","unit":1,"saveAsUnit":2,"categoryName":"Pulses & Lentils"},

  {"name":"Basmati Rice","unit":1,"saveAsUnit":2,"categoryName":"Grains & Rice"},
  {"name":"Long Grain Rice","unit":1,"saveAsUnit":2,"categoryName":"Grains & Rice"},
  {"name":"Short Grain Rice","unit":1,"saveAsUnit":2,"categoryName":"Grains & Rice"},
  {"name":"Parboiled Rice","unit":1,"saveAsUnit":2,"categoryName":"Grains & Rice"},
  {"name":"Broken Rice","unit":1,"saveAsUnit":2,"categoryName":"Grains & Rice"},
  {"name":"Arborio (Risotto) Rice","unit":1,"saveAsUnit":2,"categoryName":"Grains & Rice"},
  {"name":"Sushi Rice","unit":1,"saveAsUnit":2,"categoryName":"Grains & Rice"},
  {"name":"Rice Flour","unit":1,"saveAsUnit":2,"categoryName":"Grains & Rice"},

  {"name":"Wheat Flour (Atta)","unit":1,"saveAsUnit":2,"categoryName":"Flours & Cereals"},
  {"name":"Maida (Refined Flour)","unit":1,"saveAsUnit":2,"categoryName":"Flours & Cereals"},
  {"name":"Semolina (Rava)","unit":1,"saveAsUnit":2,"categoryName":"Flours & Cereals"},
  {"name":"Corn Flour","unit":1,"saveAsUnit":2,"categoryName":"Flours & Cereals"},
  {"name":"Gram Flour (Besan)","unit":1,"saveAsUnit":2,"categoryName":"Flours & Cereals"},
  {"name":"Oats (Rolled)","unit":1,"saveAsUnit":2,"categoryName":"Flours & Cereals"},
  {"name":"Muesli (raw)","unit":1,"saveAsUnit":2,"categoryName":"Flours & Cereals"},
  {"name":"Breadcrumbs (raw)","unit":1,"saveAsUnit":2,"categoryName":"Flours & Cereals"},

  {"name":"Salt (Table)","unit":1,"saveAsUnit":1,"categoryName":"Spices & Masalas"},
  {"name":"Black Pepper Powder","unit":1,"saveAsUnit":1,"categoryName":"Spices & Masalas"},
  {"name":"Red Chilli Powder","unit":1,"saveAsUnit":1,"categoryName":"Spices & Masalas"},
  {"name":"Turmeric Powder","unit":1,"saveAsUnit":1,"categoryName":"Spices & Masalas"},
  {"name":"Cumin Powder","unit":1,"saveAsUnit":1,"categoryName":"Spices & Masalas"},
  {"name":"Coriander Powder","unit":1,"saveAsUnit":1,"categoryName":"Spices & Masalas"},
  {"name":"Garam Masala","unit":1,"saveAsUnit":1,"categoryName":"Spices & Masalas"},
  {"name":"Chaat Masala","unit":1,"saveAsUnit":1,"categoryName":"Spices & Masalas"},
  {"name":"Cinnamon Powder","unit":1,"saveAsUnit":1,"categoryName":"Spices & Masalas"},
  {"name":"Nutmeg Powder","unit":1,"saveAsUnit":1,"categoryName":"Spices & Masalas"},
  {"name":"Clove Powder","unit":1,"saveAsUnit":1,"categoryName":"Spices & Masalas"},
  {"name":"Fenugreek Powder","unit":1,"saveAsUnit":1,"categoryName":"Spices & Masalas"},
  {"name":"Five Spice Powder","unit":1,"saveAsUnit":1,"categoryName":"Spices & Masalas"},
  {"name":"Sichuan Pepper","unit":1,"saveAsUnit":1,"categoryName":"Spices & Masalas"},
  {"name":"Paprika","unit":1,"saveAsUnit":1,"categoryName":"Spices & Masalas"},
  {"name":"Dried Oregano","unit":1,"saveAsUnit":1,"categoryName":"Spices & Masalas"},
  {"name":"Dried Basil","unit":1,"saveAsUnit":1,"categoryName":"Spices & Masalas"},
  {"name":"Curry Powder","unit":1,"saveAsUnit":1,"categoryName":"Spices & Masalas"},

  {"name":"Fresh Coriander (cilantro)","unit":1,"saveAsUnit":1,"categoryName":"Herbs & Seasonings"},
  {"name":"Fresh Mint","unit":1,"saveAsUnit":1,"categoryName":"Herbs & Seasonings"},
  {"name":"Rosemary (dried)","unit":1,"saveAsUnit":1,"categoryName":"Herbs & Seasonings"},
  {"name":"Thyme (dried)","unit":1,"saveAsUnit":1,"categoryName":"Herbs & Seasonings"},
  {"name":"Bay Leaves","unit":1,"saveAsUnit":1,"categoryName":"Herbs & Seasonings"},
  {"name":"Parsley (dried)","unit":1,"saveAsUnit":1,"categoryName":"Herbs & Seasonings"},
  {"name":"Chives (fresh)","unit":1,"saveAsUnit":1,"categoryName":"Herbs & Seasonings"},
  {"name":"Dill (fresh/dried)","unit":1,"saveAsUnit":1,"categoryName":"Herbs & Seasonings"},
  {"name":"Saffron (small pack)","unit":1,"saveAsUnit":1,"categoryName":"Herbs & Seasonings"},

  {"name":"Refined Vegetable Oil","unit":4,"saveAsUnit":3,"categoryName":"Oils & Fats"},
  {"name":"Sunflower Oil","unit":4,"saveAsUnit":3,"categoryName":"Oils & Fats"},
  {"name":"Canola Oil","unit":4,"saveAsUnit":3,"categoryName":"Oils & Fats"},
  {"name":"Olive Oil (Extra Virgin)","unit":4,"saveAsUnit":3,"categoryName":"Oils & Fats"},
  {"name":"Mustard Oil","unit":4,"saveAsUnit":3,"categoryName":"Oils & Fats"},
  {"name":"Ghee (Clarified Butter)","unit":4,"saveAsUnit":3,"categoryName":"Oils & Fats"},
  {"name":"Butter (block)","unit":1,"saveAsUnit":1,"categoryName":"Oils & Fats"},

  {"name":"Milk (Fresh)","unit":4,"saveAsUnit":3,"categoryName":"Dairy & Milk Products"},
  {"name":"Full Cream Milk (UHT)","unit":4,"saveAsUnit":3,"categoryName":"Dairy & Milk Products"},
  {"name":"Skimmed Milk","unit":4,"saveAsUnit":3,"categoryName":"Dairy & Milk Products"},
  {"name":"Cream (Fresh)","unit":4,"saveAsUnit":3,"categoryName":"Dairy & Milk Products"},
  {"name":"Butter (unsalted)","unit":1,"saveAsUnit":1,"categoryName":"Dairy & Milk Products"},
  {"name":"Cheddar Cheese (block)","unit":1,"saveAsUnit":1,"categoryName":"Dairy & Milk Products"},
  {"name":"Mozzarella Cheese (block)","unit":1,"saveAsUnit":1,"categoryName":"Dairy & Milk Products"},
  {"name":"Paneer (Cottage Cheese)","unit":1,"saveAsUnit":1,"categoryName":"Dairy & Milk Products"},
  {"name":"Yogurt (Curd)","unit":4,"saveAsUnit":3,"categoryName":"Dairy & Milk Products"},
  {"name":"Buttermilk (Chaas)","unit":4,"saveAsUnit":3,"categoryName":"Dairy & Milk Products"},
  {"name":"Condensed Milk","unit":1,"saveAsUnit":1,"categoryName":"Dairy & Milk Products"},
  {"name":"Milk Powder (Full Fat)","unit":1,"saveAsUnit":1,"categoryName":"Dairy & Milk Products"},

  {"name":"Bread Loaf (plain) - raw","unit":5,"saveAsUnit":5,"categoryName":"Bread & Bakery Raw"},
  {"name":"Burger Buns (raw)","unit":5,"saveAsUnit":5,"categoryName":"Bread & Bakery Raw"},
  {"name":"Pita Bread (raw)","unit":5,"saveAsUnit":5,"categoryName":"Bread & Bakery Raw"},
  {"name":"Pizza Base (par-baked)","unit":5,"saveAsUnit":5,"categoryName":"Bread & Bakery Raw"},
  {"name":"Baguette (raw)","unit":5,"saveAsUnit":5,"categoryName":"Bread & Bakery Raw"},
  {"name":"Cake Sponge (raw)","unit":5,"saveAsUnit":5,"categoryName":"Bread & Bakery Raw"},
  {"name":"Croissant Dough (raw)","unit":5,"saveAsUnit":5,"categoryName":"Bread & Bakery Raw"},
  {"name":"Dough Mix (pizza)","unit":1,"saveAsUnit":2,"categoryName":"Bread & Bakery Raw"},

  {"name":"Beef (boneless)","unit":1,"saveAsUnit":2,"categoryName":"Meat"},
  {"name":"Beef (bone-in)","unit":1,"saveAsUnit":2,"categoryName":"Meat"},
  {"name":"Mutton (goat)","unit":1,"saveAsUnit":2,"categoryName":"Meat"},
  {"name":"Lamb (cuts)","unit":1,"saveAsUnit":2,"categoryName":"Meat"},
  {"name":"Pork (cuts)","unit":1,"saveAsUnit":2,"categoryName":"Meat"},
  {"name":"Bacon (raw)","unit":1,"saveAsUnit":2,"categoryName":"Meat"},
  {"name":"Sausage (raw)","unit":1,"saveAsUnit":2,"categoryName":"Meat"},

  {"name":"Whole Chicken","unit":1,"saveAsUnit":2,"categoryName":"Poultry"},
  {"name":"Chicken Breast (boneless)","unit":1,"saveAsUnit":2,"categoryName":"Poultry"},
  {"name":"Chicken Thigh","unit":1,"saveAsUnit":2,"categoryName":"Poultry"},
  {"name":"Chicken Drumstick","unit":1,"saveAsUnit":2,"categoryName":"Poultry"},
  {"name":"Turkey (cuts)","unit":1,"saveAsUnit":2,"categoryName":"Poultry"},
  {"name":"Duck (whole)","unit":1,"saveAsUnit":2,"categoryName":"Poultry"},

  {"name":"Fish Fillet (white fish)","unit":1,"saveAsUnit":2,"categoryName":"Seafood"},
  {"name":"Salmon Fillet","unit":1,"saveAsUnit":2,"categoryName":"Seafood"},
  {"name":"Prawns (peeled)","unit":1,"saveAsUnit":2,"categoryName":"Seafood"},
  {"name":"Whole Fish (pomfret/rohu)","unit":1,"saveAsUnit":2,"categoryName":"Seafood"},
  {"name":"Squid (cleaned)","unit":1,"saveAsUnit":2,"categoryName":"Seafood"},
  {"name":"Crab (cleaned)","unit":1,"saveAsUnit":2,"categoryName":"Seafood"},

  {"name":"Eggs (large)","unit":5,"saveAsUnit":5,"categoryName":"Eggs & Egg Products"},
  {"name":"Liquid Egg (pasteurized)","unit":4,"saveAsUnit":3,"categoryName":"Eggs & Egg Products"},
  {"name":"Egg Powder","unit":1,"saveAsUnit":1,"categoryName":"Eggs & Egg Products"},

  {"name":"Tomato Ketchup (bulk)","unit":4,"saveAsUnit":3,"categoryName":"Sauces & Pastes"},
  {"name":"Soya Sauce","unit":4,"saveAsUnit":3,"categoryName":"Sauces & Pastes"},
  {"name":"Vinegar (white)","unit":4,"saveAsUnit":3,"categoryName":"Sauces & Pastes"},
  {"name":"Vinegar (malt)","unit":4,"saveAsUnit":3,"categoryName":"Sauces & Pastes"},
  {"name":"Ginger Garlic Paste","unit":4,"saveAsUnit":3,"categoryName":"Sauces & Pastes"},
  {"name":"Chilli Sauce","unit":4,"saveAsUnit":3,"categoryName":"Sauces & Pastes"},
  {"name":"Mayonnaise (bulk)","unit":4,"saveAsUnit":3,"categoryName":"Sauces & Pastes"},
  {"name":"BBQ Sauce","unit":4,"saveAsUnit":3,"categoryName":"Sauces & Pastes"},
  {"name":"Pesto Sauce","unit":4,"saveAsUnit":3,"categoryName":"Sauces & Pastes"},
  {"name":"Curry Paste (Thai)","unit":4,"saveAsUnit":3,"categoryName":"Sauces & Pastes"},

  {"name":"Paneer Tikka Mix (premix)","unit":1,"saveAsUnit":2,"categoryName":"Ready Mix / Premix"},
  {"name":"Bread Crumb Mix","unit":1,"saveAsUnit":2,"categoryName":"Ready Mix / Premix"},
  {"name":"Cake Mix (vanilla)","unit":1,"saveAsUnit":2,"categoryName":"Ready Mix / Premix"},
  {"name":"Custard Powder","unit":1,"saveAsUnit":1,"categoryName":"Ready Mix / Premix"},
  {"name":"Pizza Seasoning Mix","unit":1,"saveAsUnit":1,"categoryName":"Ready Mix / Premix"},

  {"name":"Canned Tomatoes","unit":4,"saveAsUnit":3,"categoryName":"Canned & Preserved Goods"},
  {"name":"Canned Beans","unit":4,"saveAsUnit":3,"categoryName":"Canned & Preserved Goods"},
  {"name":"Canned Corn","unit":4,"saveAsUnit":3,"categoryName":"Canned & Preserved Goods"},
  {"name":"Canned Pineapple","unit":4,"saveAsUnit":3,"categoryName":"Canned & Preserved Goods"},
  {"name":"Pickles (mango)","unit":4,"saveAsUnit":3,"categoryName":"Canned & Preserved Goods"},
  {"name":"Olives (jar)","unit":4,"saveAsUnit":3,"categoryName":"Canned & Preserved Goods"},
  {"name":"Canned Coconut Milk","unit":4,"saveAsUnit":3,"categoryName":"Canned & Preserved Goods"},

  {"name":"Frozen Peas","unit":1,"saveAsUnit":2,"categoryName":"Frozen Raw Materials"},
  {"name":"Frozen Corn","unit":1,"saveAsUnit":2,"categoryName":"Frozen Raw Materials"},
  {"name":"Frozen Mixed Vegetables","unit":1,"saveAsUnit":2,"categoryName":"Frozen Raw Materials"},
  {"name":"Frozen French Fries (potato)","unit":1,"saveAsUnit":2,"categoryName":"Frozen Raw Materials"},
  {"name":"Frozen Chicken Nuggets","unit":1,"saveAsUnit":2,"categoryName":"Frozen Raw Materials"},
  {"name":"Frozen Fish Fingers","unit":1,"saveAsUnit":2,"categoryName":"Frozen Raw Materials"},
  {"name":"Frozen Parathas","unit":1,"saveAsUnit":2,"categoryName":"Frozen Raw Materials"},

  {"name":"Almonds (raw)","unit":1,"saveAsUnit":1,"categoryName":"Dry Fruits & Nuts"},
  {"name":"Cashews (raw)","unit":1,"saveAsUnit":1,"categoryName":"Dry Fruits & Nuts"},
  {"name":"Raisins (Kishmish)","unit":1,"saveAsUnit":1,"categoryName":"Dry Fruits & Nuts"},
  {"name":"Walnuts","unit":1,"saveAsUnit":1,"categoryName":"Dry Fruits & Nuts"},
  {"name":"Pistachios","unit":1,"saveAsUnit":1,"categoryName":"Dry Fruits & Nuts"},
  {"name":"Peanuts (raw)","unit":1,"saveAsUnit":1,"categoryName":"Dry Fruits & Nuts"},

  {"name":"Dishwashing Liquid","unit":4,"saveAsUnit":3,"categoryName":"Cleaning & Consumables"},
  {"name":"Sanitizer (bulk)","unit":4,"saveAsUnit":3,"categoryName":"Cleaning & Consumables"},
  {"name":"Bleach (liquid)","unit":4,"saveAsUnit":3,"categoryName":"Cleaning & Consumables"},
  {"name":"Surface Cleaner","unit":4,"saveAsUnit":3,"categoryName":"Cleaning & Consumables"},
  {"name":"Degreaser","unit":4,"saveAsUnit":3,"categoryName":"Cleaning & Consumables"},
  {"name":"Oven Cleaner","unit":4,"saveAsUnit":3,"categoryName":"Cleaning & Consumables"},
  {"name":"Scouring Powder","unit":1,"saveAsUnit":1,"categoryName":"Cleaning & Consumables"},
  {"name":"Hand Wash Liquid","unit":4,"saveAsUnit":3,"categoryName":"Cleaning & Consumables"},
  {"name":"Glass Cleaner","unit":4,"saveAsUnit":3,"categoryName":"Cleaning & Consumables"},
  {"name":"Garbage Bags (roll)","unit":5,"saveAsUnit":5,"categoryName":"Cleaning & Consumables"},

  {"name":"Cardboard Boxes (pack)","unit":5,"saveAsUnit":5,"categoryName":"Packaging Materials"},
  {"name":"Plastic Food Containers (bulk)","unit":5,"saveAsUnit":5,"categoryName":"Packaging Materials"},
  {"name":"Aluminium Foil (roll)","unit":5,"saveAsUnit":5,"categoryName":"Packaging Materials"},
  {"name":"Cling Film (roll)","unit":5,"saveAsUnit":5,"categoryName":"Packaging Materials"},
  {"name":"Paper Bags (takeaway)","unit":5,"saveAsUnit":5,"categoryName":"Packaging Materials"},
  {"name":"Sachet Packaging (ketchup)","unit":5,"saveAsUnit":5,"categoryName":"Packaging Materials"},

  {"name":"Disposable Cutlery (spoons/forks)","unit":5,"saveAsUnit":5,"categoryName":"Disposables"},
  {"name":"Disposable Plates (paper)","unit":5,"saveAsUnit":5,"categoryName":"Disposables"},
  {"name":"Disposable Cups (paper)","unit":5,"saveAsUnit":5,"categoryName":"Disposables"},
  {"name":"Takeaway Boxes (foam/cardboard)","unit":5,"saveAsUnit":5,"categoryName":"Disposables"},
  {"name":"Straws (paper/plastic)","unit":5,"saveAsUnit":5,"categoryName":"Disposables"},
  {"name":"Napkins (paper)","unit":5,"saveAsUnit":5,"categoryName":"Disposables"},

  {"name":"Food Grade Sodium Bicarbonate","unit":1,"saveAsUnit":1,"categoryName":"Chemicals (Kitchen Use)"},
  {"name":"Citric Acid (food grade)","unit":1,"saveAsUnit":1,"categoryName":"Chemicals (Kitchen Use)"},
  {"name":"Potassium Metabisulphite (food grade)","unit":1,"saveAsUnit":1,"categoryName":"Chemicals (Kitchen Use)"},
  {"name":"Industrial Salt (for brine)","unit":1,"saveAsUnit":1,"categoryName":"Chemicals (Kitchen Use)"},
  {"name":"Food Grade Hydrogen Peroxide (low %)","unit":4,"saveAsUnit":3,"categoryName":"Chemicals (Kitchen Use)"}
]

